
NDK_BUILD= /home/taotao/Dev/Tools/android-ndk-r4b/ndk-build
PROJ_DIR = /media/34D0110AD010D448/Interested/FBReaderJ/jni
START =	FBReaderJ

$(START):
	cd $(PROJ_DIR);$(NDK_BUILD) V=1

all:	$(START)

clean:
	cd $(PROJ_DIR);$(NDK_BUILD) clean
